- checks/Instance.Tests.ps1
Compression, not compreesion :)
> Variable typos

- checks/Agent.Tests.ps1
- internal/configurations/configuration.ps1
> Output job status, not always "success"

- checks/Agent.Tests.ps1
- internal/configurations/configuration.ps1
> New Check - Job Owner check

- functions/Start-DbcPowerBi.ps1
> remove validation - let windows handle it

- functions/Send-DbcMailMessage.ps1
- Detailed page isn't viewable otherwise
- Fix comment typo
- Resolves #309
> Attach HTML report to Mail

- checks/Agent.Tests.ps1
Fixes bug #317
Altered to look for the databasemail at .JobServer.DatabaseMailProfile instead of .JobServer.AlertSystem.DatabaseMailProfile
> Need to check the correct property

- checks/Database.Tests.ps1
- dbachecks.psd1
Fixes #332 
- Changed to use Test-DbaDbVirtualLogFile
- Upped required dbatools version to 0.9.300
> Change VLF test name

- checks/Database.Tests.ps1
Added test to make sure the database compatibility level matches that of the server version.
> New check - database compatibility level - closes #333

- internal/functions/Get-DatabaseDetail.ps1
- tests/Get-DatabaseDetail.Tests.ps1
This pull requests is the first one on the way to implementing to what I outlined in the issue #316 comments. That is the part which will have to be integration tested on different versions of SQL server, but also a part to which I will use again and again in a number of PR's I'm going to prepare, so I thought I will put it out there and hopefully after going through the scrutiny here first, will help me with the rest of the work when it makes its way to development branch. 
There are only two files in this pull request and no changes to anything existing.
> T-SQL to collect basic database configuration for faster checks

- checks/Database.Tests.ps1
- dbachecks.psd1
- readme.md
Validation was missing.
Add line 258 to fix #297.
> Add 'skip.diffbackuptest' validation

- checks/MaintenanceSolution.Tests.ps1
- internal/scripts/postimport.ps1
Horrifyingly enough, `MaintenanceSolution` was listed as `MaintenancePlan` 
Also, all of the ola jobs have Ola prepended and that wasnt listed either
> MaintenanceSolution fix

- checks/Database.Tests.ps1
- checks/MaintenanceSolution.Tests.ps1
> Fixes PS4 issue

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
Adding a check for the expiration of TDE certificates in databases.
I'm unsure the policy config names should be under policy.database.xxx or remain as is, since the database exclusion is at the server level, but the check itself is at the database level...
Database exclusion for this check is a little kludgy, but was having trouble getting more straightforward approaches to work properly for some reason.
> New Check: Certificate Expiration

- internal/functions/Get-SqlInstance.ps1
This should work as seen in the screenshot below
> Force array from Get-SqlInstance

- checks/Database.Tests.ps1
Fixed issue 369 by updating the line to be an array.
> issue369_js0505

- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
We missed an array on Instance Tests for Dedicated Administrator Connection. I have updated it.
> Issue371 js0505

- checks/Instance.Tests.ps1
- internal/configurations/configuration.ps1
- tests/Unit.Tests.ps1
> modeldb growth settings

- checks/Agent.Tests.ps1
- internal/configurations/configuration.ps1
> enabled check for multiple Agent job owners

- dbachecks.psd1
Thank you @frank687 and @wsmelton
> Enabling checking multiple Job owners and some readme updates

- dbachecks.psd1
one day I will get VSTS to do this properly
> Updated Version Number to 1.1.110 ***NO_CI***

- dbachecks.psd1
> Database Owners can now be an array

- checks/Instance.Tests.ps1
- internal/configurations/configuration.ps1
> Adding error log check

- checks/Agent.Tests.ps1
- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- checks/LogShipping.Tests.ps1
- checks/MaintenanceSolution.Tests.ps1
- checks/Server.Tests.ps1
- internal/functions/Get-SqlInstance.ps1
- internal/scripts/postimport.ps1
- tests/Unit.Tests.ps1
- tests/checks/Test.Database.Tests.ps1
SOme imporvements to performance by just passing the database name instead of getting the entire database smo object to only pass the name
> Just get database name

- checks/Agent.Tests.ps1
- checks/Instance.Tests.ps1
- dbachecks.psd1
- tests/Get-DbcCheck.Tests.ps1
Thank you @PsPsam 
and also altered a couple of tests to make the VSTS output easier to handle
> Added new test for AD users

- checks/Database.Tests.ps1
> Fixes backup test error and typos 

- dbachecks.psd1
> updated required versions

- checks/Instance.Tests.ps1
> this will speed up the check by not making ans many calls

- checks/Instance.Tests.ps1
- tests/Unit.Tests.ps1
Passed the Unit Tests and happy to go to Live - Demonstrated at Nottingham PowerShell User Group (in a pub!)
> Browser Speed improvement

- checks/HADR.Tests.ps1
> Hadr multi subnet

- checks/Database.Tests.ps1
> fixed secondary read only error

- checks/Agent.Tests.ps1
> Changes to fix a couple of issues with AgentAlerts 

- dbachecks.psd1
> improvements to agent checks by jpomfret

- dbachecks.psd1
- functions/Reset-DbcConfig.ps1
- internal/configurations/configuration.ps1
- internal/functions/Invoke-ConfigurationScript.ps1
- tests/Reset-DbcConfig.Tests.ps1
resolves #337 by wrapping the `Unregister-PSFConfig`
> New command: Reset-DbcConfig

- dbachecks.psd1
- functions/Reset-DbcConfig.ps1
- internal/configurations/configuration.ps1
- internal/functions/Invoke-ConfigurationScript.ps1
- tests/Reset-DbcConfig.Tests.ps1
I think I fixed the problem with the previous build but since both times it was passing in my environment I have to try merging and building dev again
> New command: Reset-DbcConfig - second take

- checks/Domain.Tests.ps1
- checks/Instance.Tests.ps1
- functions/Get-DbcCheck.ps1
- internal/functions/New-Json.ps1
- internal/scripts/postimport.ps1
- xml/dbachecks.Format.ps1xml
> Getdbccheck with configs

- checks/HADR.Tests.ps1
> added multi port support to check

- dbachecks.psd1
> Added fix for express edition

- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- checks/MaintenanceSolution.Tests.ps1
- functions/Clear-DbcPowerBiDataSource.ps1
- functions/Get-DbcCheck.ps1
- functions/Invoke-DbcCheck.ps1
- functions/Send-DbcMailMessage.ps1
- functions/Set-DbcConfig.ps1
- functions/Start-DbcPowerBi.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/functions/New-Json.ps1
- tests/InModule.Help.Tests.ps1
- tests/Unit.Tests.ps1
- tests/functions/Get-DatabaseDetail.Tests.ps1
- xml/dbachecks.Format.ps1xml
Added descriptions for the checks using the json file
Altered output of get-dbccheck to show descriptionis last int he view
Added tests for the descriptions
fixed help test to check dbachecks instead of dbatools!
Fixed help tests to ignore common parameters
Fixed help for failing help tests
> Dbccheck config

- checks/Server.Tests.ps1
- internal/assertions/Server.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- tests/checks/ServerChecks.Tests.ps1
Please add below the changes that this PR covers. It doesn't need an essay just the bullet points :-)
Added test to check disk block allocation unit on each drive meets the 64KB recommended best practise.
> New check for drive block allocation unit.

- internal/configurations/DbcCheckDescriptions.json
[]X There are 0 failing Pester tests
Fixed some of the spelling
> corrected spelling

- checks/Instance.Tests.ps1
- dbachecks.psd1
Updated command name and required module, otherwise you'll see a big ol warning about a deprecated command name
Updated command name and required module, otherwise you'll see a big ol warning about a deprecated command name. Please merge if it's acceptable cuz I don't know the process ;D
> update command name and requiredmodule

- checks/Instance.Tests.ps1
> Fix Orphan File command name

- dbachecks.psd1
Updated to most recent versions of dbatools
* PS v3 support added back recently
* fixed windows auth issues
Updated to most recent versions of PSFramework
* PS v3 support added back recently
Updated to most recent version of Pester
* because it seems like a good time to update since others are updating
* it no longer says "first describe only whatever for now"
@SQLDBAWithABeard - I tested just a few things with the new pester and all seems good but it could use some additional testing.
> Updated all required modules

- checks/Agent.Tests.ps1
- checks/HADR.Tests.ps1
- dbachecks.psd1
- internal/configurations/ReleaseNotes.txt
- tests/Unit.Tests.ps1
> New PR for updated agent checks and updated module versions

- checks/Agent.Tests.ps1
- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- checks/Server.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/ReleaseNotes.txt
- tests/checks/InstanceChecks.Tests.ps1
Added New Check for tempdb data file sizes to be the same - Thank you @garethnewman #512
Altered Services Check so that clustered instances start mode is checked correctly thank you @kylejdoyle #516
Skip PowerPlan test if no connection thanks @cl #490
Fixed bug with XESession and PSv4 thank you @kylejdoyle #517
Error silently on failing Service check (thanks Rob ;-) )
Fixed dbatools command names
> New Checks and Bug fixes

- checks/Agent.Tests.ps1
- checks/Database.Tests.ps1
- checks/HADR.Tests.ps1
- checks/Instance.Tests.ps1
- checks/Server.Tests.ps1
- dbachecks.psd1
- functions/Get-DbcCheck.ps1
- functions/Invoke-DbcCheck.ps1
- functions/Update-DbcPowerBiDataSource.ps1
- internal/assertions/Server.Assertions.ps1
- internal/configurations/ReleaseNotes.txt
- internal/configurations/configuration.ps1
- internal/functions/Get-CheckFile.ps1
- internal/functions/Get-CheckInformation.ps1
- internal/functions/New-Json.ps1
- tests/Unit.Tests.ps1
- tests/functions/Get-CheckInformation.tests.ps1
- tests/functions/Invoke-DbcCheck.Tests.ps1
- tests/functions/get-check.json
> Mainly psv4 fixes and custome name

- checks/Server.Tests.ps1
- internal/configurations/ReleaseNotes.txt
- internal/functions/Get-CheckFile.ps1
- internal/functions/New-Json.ps1
Added loop to the file instead of the checks and improved performance by about 60% for the Server checks
> Increase performance of Server tests

- checks/Database.Tests.ps1
and now its fixed ;-)
https://twitter.com/sqldbawithbeard/status/1029822270427017217
> ok this was the 'bug'

- functions/Update-DbcPowerBiDataSource.ps1
If environment is specified it wasnt naming hte file .json and therefore PowerBi wasnt picking it up
> Need to have the file named .json to be picked up

- checks/HADR.Tests.ps1
* Fixing typo in suggested command to run.
> config name is singular, not plural

- dbachecks.psd1
- functions/Invoke-DbcCheck.ps1
- internal/configurations/ReleaseNotes.txt
> putting #532 into master

- internal/assertions/Instance.Assertions.ps1
Reverts sqlcollaborative/dbachecks#538
We can't have It's inside the asserts
> Revert "Fixing blocks for each SupportedBuild test"

- checks/Agent.Tests.ps1
- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- checks/Server.Tests.ps1
- dbachecks.psd1
- functions/Invoke-DbcCheck.ps1
- functions/Update-DbcPowerBiDataSource.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/assertions/Server.Assertions.ps1
- internal/configurations/ReleaseNotes.txt
- internal/functions/Select-DefaultView.ps1
- tests/checks/InstanceChecks.Tests.ps1
- tests/checks/ServerChecks.Tests.ps1
Next release with dbatools command updates and server check improvements
> Next release with dbatools command updates and server check improvements

- checks/Instance.Tests.ps1
- checks/Server.Tests.ps1
- dbachecks.psd1
- functions/Invoke-DbcCheck.ps1
- functions/Set-DbcConfig.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/ReleaseNotes.txt
- internal/configurations/configuration.ps1
- tests/Unit.Tests.ps1
- tests/checks/InstanceChecks.Tests.ps1
> traceflags

- RELEASE.md
- readme.md
This corrects minor spelling issues on readme.md and release.md only.
> Spelling corrections only to md files

- functions/Import-DbcConfig.ps1
Happened on dbatools already, fix was easy peasy
> fixes #564

- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- checks/MaintenanceSolution.Tests.ps1
- checks/Server.Tests.ps1
- Fixes https://github.com/sqlcollaborative/dbachecks/issues/566
- Add instance/computer name to "It" blocks where it was missing. It was hard reading the Power BI grid to know some errors belongs to which instance.
> Fix Database Status check & Add instance/computer to it blocks

- checks/Database.Tests.ps1
Fixed typoes in Auto Create Statistics, Auto Update Statistics and Auto Update Statistics Asynchronously at -Because
Fixed typoes in Auto Create Statistics, Auto Update Statistics and Auto Update Statistics Asynchronously at -Because
> Fixed some typos in Database.test

- checks/Instance.Tests.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
Check for number of files configured to Error Log
> Error log count check

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/checks/InstanceChecks.Tests.ps1
@SQLDBAWithABeard Let me know if it is ok.
Thanks
> Error log count check - Change to assert function

- checks/Instance.Tests.ps1
- internal/configurations/configuration.ps1
adds ability to skip Authentication scheme - closes #587
> Skip authscheme

- functions/Update-DbcPowerBiDataSource.ps1
> fix default environment name in powerbi

- checks/Database.Tests.ps1
- dbachecks.psd1
> updated command name, updated all dependent module versions

- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- dbachecks.psd1
- functions/Update-DbcPowerBiDataSource.ps1
- internal/assertions/Instance.Assertions.ps1
- tests/checks/InstanceChecks.Tests.ps1
> Time for an update

- checks/Database.Tests.ps1
- tests/Integration/DockerTests.ps1
Fixes #612 - Removed Offline databases from the Pseudosimple check.
> Removed offline databases from PseudoSimple checks.

- checks/Database.Tests.ps1
- checks/HADR.Tests.ps1
- docs/functions/Clear-DbcPowerBiDataSource.md
- docs/functions/Export-DbcConfig.md
- docs/functions/Get-DbcCheck.md
- docs/functions/Get-DbcConfig.md
- docs/functions/Get-DbcConfigValue.md
- docs/functions/Get-DbcTagCollection.md
- docs/functions/Import-DbcConfig.md
- docs/functions/Invoke-DbcCheck.md
- docs/functions/Invoke-DbcConfigFile.md
- docs/functions/Reset-DbcConfig.md
- docs/functions/Save-DbcRequiredModules.md
- docs/functions/Set-DbcConfig.md
- docs/functions/Start-DbcPowerBi.md
- docs/functions/Update-DbcPowerBiDataSource.md
- docs/functions/Update-DbcRequiredModules.md
- readme.md
- tests/Integration/DockerTests.ps1
All of the good stuff for techorama
> so that the release notes are shown

- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- checks/LogShipping.Tests.ps1
- docs/functions/Update-DbcPowerBiDataSource.md
- functions/Update-DbcPowerBiDataSource.ps1
- internal/assertions/Database.Assertions.ps1
- internal/assertions/Instance.Assertions.ps1
- tests/checks/AgentChecks.Tests.ps1
- tests/checks/DatabaseChecks.Tests.ps1
- tests/checks/InstanceChecks.Tests.ps1
* Ran Invoke-DbatoolsRenameHelper on dbachecks module
Addresses #624
> dbachecks uses dbatools 1.0 commands

- internal/assertions/Instance.Assertions.ps1
> Add check of Error.LogDate

- internal/assertions/Instance.Assertions.ps1
> Only check current element of $tags array, not all elements

- checks/MaintenanceSolution.Tests.ps1
> $Matches doesn't work that way.

- functions/Start-DbcPowerBi.ps1
> removed rogue parameter

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/assertions/Server.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- internal/functions/New-Json.ps1
- internal/scripts/postimport.ps1
- tests/checks/InstanceChecks.Tests.ps1
Added new default trace check
unfortunately cant add CIS tag as my pester requires one tag per check file (this I should look at !!)
> Cis defaulttrac

- tests/Unit.Tests.ps1
> Load module under test before tests, not after

- readme.md
Fixed sending mail documentation (#704)
> fixed send mail bug in readme.md #704

- checks/Agent.Tests.ps1
- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/checks/InstanceChecks.Tests.ps1
Well the assertion for Default Trace doesn't exist so I do have failing but I didn't do it.
Test for remote access to be disabled for CIS and tagging Database Mail XPs for CIS.
> Issue 650 - CIS Remote access

- functions/Start-DbcPowerBi.ps1
> Removed example with removed parameter.

- checks/Agent.Tests.ps1
- tests/Unit.Tests.ps1
> Fixes #713

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/checks/InstanceChecks.Tests.ps1
Added configurable sql engine servicechecks and created assertions
> Configurable engine checks

- readme.md
Just adding a link to(and for) a new blog post
> So that people can find the guide to forking and creating a PR

- checks/Agent.Tests.ps1
The longrunning agent job describe block was inside another describe block and in the wrong place
> embedded agent job describe block error

- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
-Checks databases except master, tempdb, and msdb to see if guest users has CONNECT permission.  
-By default I set this up as skip test but that can changed just let me know.
> CIS check guest account CONNECT permissions

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- CIS test for whether BUILTIN\Adminstrations login exists or not
> CIS test for whether BUILTIN\Adminstrations login exists or not

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- CIS test that public server role only has default permissions
> CIS check for public role permissions

- internal/assertions/Instance.Assertions.ps1
- Change disabled sa check from a query to use proper command Get-DbaLogin (I learned more stuff)
> Do sa disable check the right way with Get-DbaLogin

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- CIS test for audit recording of failed logins 
- CIS test for audit recording of successful and failed logins
> Audit level CIS tests

- RELEASE.md
- checks/Database.Tests.ps1
- checks/HADR.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
This is actually #734 which for some reason has decided to have its own branch this time
> Tboggiano clrsafe

- PSScriptAnalyzerSettings.psd1
- RELEASE.md
- checks/Agent.Tests.ps1
- checks/Database.Tests.ps1
- checks/HADR.Tests.ps1
- checks/Instance.Tests.ps1
- checks/Server.Tests.ps1
- dbachecks.psd1
- docs/RELEASE.md
- docs/functions/Invoke-DbcCheck.md
- internal/assertions/Database.Assertions.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/Unit.Tests.ps1
- tests/checks/InstanceChecks.Tests.ps1
- workspace.code-workspace
> added a load of fantastic PRs

- RELEASE.md
- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- Checks that query store not off or in error state.
- CIS test for if you have a contained database it has no SQL authenticated users
Close #745 
Close #690 
Close #744 
Close #661 
> New PR for Query Store and Contained Users

- checks/HADR.Tests.ps1
- Just spotted a typo while I was running these life saving tests! 😊
> Couple of Typos

- .github/workflows/PR-PesterTest.yml
> import pester v4

- .github/workflows/PR-PesterTest.yml
- RELEASE.md
- dbachecks.psd1
- docs/RELEASE.md
- docs/functions/Invoke-DbcCheck.md
> put it live

- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
For some reason my fork wouldnt update from origin development and causing issues.
Deleted and started a fresh.
> Fixes for bug 780 & 783

- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- internal/assertions/Instance.Assertions.ps1
> Fix local windows groups, additional filter needed on the object filter

- RELEASE.md
- docs/RELEASE.md
- docs/index.md
- readme.md
Ran Unit tests locally:
- fix a couple of spelling typos in the docs
- also removed white space (setting in code on save) - let me know if you want those changes removed and I'll fix it so it's just the actual typo changes 😄
> Fixed few typos in docs

- checks/Database.Tests.ps1
Wouldnt drop into the try block, worked this out with Rob, all working as should do now
> Unused Index Check wasn't executing correctly

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
Addition of date filter to satisfy #803 was something I was working on myself also
> #803 Addition of the date filter 

- checks/Agent.Tests.ps1
Please add below the changes that this PR covers. It doesn't need an essay just the bullet points :-)
Addresses #770
> Fix the check for enabled alerts #770

- readme.md
Please add below the changes that this PR covers. It doesn't need an essay just the bullet points :-)
The previous link returned 404. Ref #343
> Updating the link as previous was 404

- functions/Get-DbcConfig.ps1
- tests/functions/Get-DbcConfig.Tests.ps1
Adding support to multiple values in -Name parameter #828 
Added test to cover this change
> Get-DbcConfig Adding support to multiple names #828

- functions/Export-DbcConfig.ps1
> Fixing typos

- PSScriptAnalyzerSettings.psd1
- functions/Export-DbcConfig.ps1
- tests/functions/Export-DbcConfig.Tests.ps1
> Get the file at the end so it can be used with Invoke-Item addresses #843

- internal/configurations/DbcCheckDescriptions.json
> Description ends with . + few redactions

- PSScriptAnalyzerSettings.psd1
- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
New CIS test for SQL Mail XPS for SQL Server 2008 and below
replaces ##779
> Cis xpmail test replaces #779

- RELEASE.md
- docs/RELEASE.md
- docs/functions/Export-DbcConfig.md
- docs/functions/Invoke-DbcCheck.md
- docs/functions/Set-DbcCisConfig.md
- mkdocs.yml
> another new release with relase notes

- functions/Convert-DbcResult.ps1
- tests/functions/Set-DbcFile.Tests.ps1
> so that we can process multiple Testresults from custom checks fixes #846

- checks/Database.Tests.ps1
- Calculating the percent as stated that it should be in issue #868
> Log file size percentage bug fix from issue 868

- .github/workflows/deploy-module.yml
- readme.md
> Adding the workflow and status badges

- .github/workflows/deploy-module.yml
> maybe this will tell us why

- RequiredModules.psd1
didn't realise I had missed it in the required.psd1
Hoping it fixes the fail to pack step of the build process
> we need PSFramework to be available

- developing/Archive/tests/functions/Export-DbcConfig.Tests.ps1
> workign on unit test

- source/checks/Instancev5.Tests.ps1
- source/functions/Export-DbcConfig.ps1
- tests/Unit/Public/Export-DbcConfig.Tests.ps1
Fixes this strange bug, no idea when it came in because I rearranged all of the files and that blows the history away.
Unit Tests added back in as well
> unit tests and correct variable - fixes #912

- .devcontainer/docker-compose.yml
New container image,  created in last pr but the container action didn't run
> Updated container image

- source/checks/Databasev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/Get-AllDatabaseInfo.ps1
putting the changes against the right branch...
> qs disabled

- .github/workflows/deploy-module.yml
- .github/workflows/docker-image.yml
So that we dont break things, keep the containers branch up to date and only build for containers on the containers branch
> Sowedontbreakthings

- .github/workflows/docker-image.yml
> because we dont need to tag the repo only the container

- source/checks/Databasev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/Get-AllDatabaseInfo.ps1
> adding shanes goodies

- containers/base/dockerfile
- containers/base/profile.ps1
definitely not so that there is a new profile and prompt - nope nope
> making changes to test the container build - HONEST

- containers/base/dockerfile
- developing/Robs-Instance.ps1
> cos we already have it

- .github/workflows/docker-image.yml
> we do need to tag the repo (we might think about this later)

- .github/workflows/docker-image.yml
> no we NEED to tag the repo for the moment

- containers/base/dockerfile
> becuase dbatools 2 wont import

- containers/JessAndBeard.psm1
- developing/Robs-Instance.ps1
- source/checks/Instancev5.Tests.ps1
- source/internal/assertions/Instance.Assertions.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/NewGet-AllInstanceInfo.ps1
> Instancecheckscontinued more checks added #882

- .devcontainer/devcontainer.json
- containers/JessAndBeard.psm1
Adding exception for GuestUserConnect - issues noted on #975 
Also added cspell to the devcontainer
> Perf validate func fix

- .vscode/settings.json
- CONTRIBUTING.md
- developing/PSConfEU demo.md
- source/checks/Databasev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/Get-AllDatabaseInfo.ps1
> PSConfEU demos and stuff

- source/checks/Databasev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/Get-AllDatabaseInfo.ps1
Tried to write this without having to query but couldn't use last log backup date as databases that were not in pseudo simple were tagged as being so.
> New v5 check: Pseudo simple

- CONTRIBUTING.md
@SQLDBAWithABeard - we accidentally merged in the draft version of `contributing.md` I created... here I've added the developing instructions but have a look and see if you like the structure - we can chat after PSConfEU
> Contribution.md - Add developing instructions

- developing/Robs-Instance.ps1
- source/checks/Instancev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/NewGet-AllInstanceInfo.ps1
> Instancecheckscontinued

- developing/Oslo Demo.ps1
> so we have a demo [no ci]

- developing/Oslo Demo.ps1
- source/checks/Databasev5.Tests.ps1
- source/internal/functions/NewGet-AllInstanceInfo.ps1
> some database check fixes #884 and instance ~882

- CHANGELOG.md
- tests/QA/module.tests.ps1
> uncomment module tests

- .vscode/settings.json
- source/checks/Databasev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/Get-AllDatabaseInfo.ps1
> adding new check for v5 fktrusted
