- checks/Instance.Tests.ps1
Changed from using InstanceName to SqlInstance so it shows name not just MSSQLSERVER for default instances. 
Fixes #331
> Fixed NetworkLatency test to report sqlInstance instead of InstanceName

- internal/functions/Set-DatabaseForIntegrationTesting.ps1
- readme.md
- tests/checks/Test.Database.Tests.ps1
While the issue #316 is still being discussed I have started writing integration tests for the database checks. 
Please review the current approach.
> Test the checks

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
I have changed the Collation test so that you can add databases by name that you want to test against the server collation. The test will now test if the database doesn't have the same collation.
Added config value name in the configuration file.
I'm not sure if it's a good or bad idea to test the given databases that they are the wrong collation. Would like some feedback on that.
Also if there is a better way to add the static db that we have excluded now or if we should move them to the wrongcollation config value?
> 351 Database Collation test

- checks/Database.Tests.ps1
- dbachecks.psd1
If the variable $wrongcollation isn't set the second test needs to be excluded. This is due to that test-dbadatabasecollation then checks all datatabases.
Added an if statement to work around this. After this change it works as I planned it to work.
Test all databases minus reportserver and reportservertempdb + $wrongcollation
If $wrongcollation is empty do not do the second test
The second test I added if to test that they really are wrong collation in the database.
> Database collation issue With test

- functions/Import-DbcConfig.ps1
- functions/Invoke-DbcConfigFile.ps1
- functions/Start-DbcPowerBi.ps1
- functions/Update-DbcPowerBiDataSource.ps1
use of `Stop-PSFunction` in catch blocks was inconsistent. Sometimes it was correctly passing the exception parameter as `-ErrorRecord`, and sometimes using `-Exception` and causing problems. 
Following @FriedrichWeinmann advice I have changed them all to `-ErrorRecord`. 
This commit resolves #379.
> Stop-PSFFunction in catch block should use -ErrorRecord

- checks/Agent.Tests.ps1
- checks/Database.Tests.ps1
This allows an array to be specified for the following config values
- policy.validdbowner.name
- policy.validdbowner.excludedb
- policy.invaliddbowner.name
- policy.invaliddbowner.excludedb
In addition the output on the ValidJobOwner test has been changed to match the format on ValidDatabaseOwner.
> Issue390 database owner config arrays

- checks/Agent.Tests.ps1
- internal/configurations/configuration.ps1
Added test for Sql Agent alerts based. It will check both for severity and message id.
Default it will check for severity 16-25 and message id 823,824 and 825
By default it will check that it will send a notification to an operator but can also check if you have a Agent job notification.
PS C:\Github\DbaChecks> invoke-pester .\tests\Unit.Tests.ps1 -Show Summary
Executing all tests in '.\tests\Unit.Tests.ps1'
Tests completed in 11.22s
Tests Passed: 684, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
> # 236 Added test for missing agent alert for Severity and MessageID

- checks/Instance.Tests.ps1
- internal/configurations/configuration.ps1
Added test for ad users and groups that are removed in the AD but not on the SQL server.
Orphaned users in the database has a test in the database checks.
Right now there can be an error for the group test in the test-dbavalidogin but the fix has been merged in dbatools [PR 3386](https://github.com/sqlcollaborative/dbatools/pull/3386) so should soon be fixed.
The test will check if the SQL login exists in the AD if it does it will do more checks so that it should work properly. It will check for password expired, locked out, enabled and if its enabled on the sql server
The test will also check ad groups if the exists in the AD and if the do check if they are enabled on the SQL server
Not sure if this covers what was asked for in Issue #238
> New test for adlogins #238

- internal/configurations/configuration.ps1
Extra "m" in Maximum ("Maxmimum") cried out for me to remove it.
> Typo fixes in configuration descriptions

- internal/configurations/configuration.ps1
- tests/Get-DatabaseDetail.Tests.ps1
- tests/Invoke-DbcCheck.Tests.ps1
Integration testing are sometimes necessary. The problem is that they typically depend on an environment. In my case, the instance names are different depending on where I work on dbachecks, and in some cases I'd like the ability to run the tests only on one instance, sometimes on multipleones. And I'd like to be able to do it without any code changes. 
And now I can, and so can you
```PowerShell
Set-DbcConfig -Name testing.integration.instance -value localhost\myinstance
```
or 
```PowerShell
Set-DbcConfig -Name testing.integration.instance -value localhost\myinstance1, localhost\myinstance2
```
All tests are passing
> Configurable SQL Instance(s) for Integration Testing

- functions/Invoke-DbcCheck.ps1
- tests/Get-DatabaseDetail.Tests.ps1
this PR changes behaviour of Inoke-DbcCheck in an event of test cancellation (ctrl+c). 
So far we were left in the custom or default repo folder. Now, with this change, even if the test is cancelled the pop-location is executed, and the location is exactly as when the execution started. As a bonus a warning message appears to notify the user that the execution was cancelled. 
All the tests have been run, no errors reported.
> pop-location after execution was cancelled

- functions/Invoke-DbcCheck.ps1
- internal/functions/Get-CheckFile.ps1
- tests/Get-CheckFile.Tests.ps1
The check files are growing in size, and with time will grow in number as well (I have two in mind already). The size of Database.Tests.ps1 makes it harder and harder to digest, and to work with, while the number of files will produce the see of green, even if we want to run just one test. 
Here is my first attempt on limiting it. If specific list of tags is provided, only the files containing those tags will be executed by Invoke-Pester. If `-Script`  or `-AllChecks` parameters are used, the behaviour is at is was. 
Have a look and please let me know what you think.
> The Sea of Green

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
Added a configuration skip.backup.readonly and logic to skip backup tests fro read-only databases
closes #468 
value set to true (note beardtest set to off-line database set to read-only
value set to false
> Backup skip readonly

- checks/Database.Tests.ps1
- dbachecks.psd1
Validate for FK & CK that should be trusted!
The dbatools commands used on this check are avaiable since v0.9.329. This should be the minimum version for this tests to work.
- Check if Foreign Keys (FK) & Check constraints (CK) are trusted!
This can have a huge performance impact on queries. 
SQL Server won’t use untrusted constraints to build better execution plans. 
Also to avoid data violation.
> Check if FK & CK are trusted

- checks/Database.Tests.ps1
The backup checks were failing on AG secondaries - decided to use isaccessible to check if the dbs should have been backed up
> dont check none-accessible databases for backups (AG secondaries)

- checks/Database.Tests.ps1
- internal/assertions/Assert-DatabaseStatus.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/Unit.Tests.ps1
- tests/checks/DatabaseChecks.Test.ps1
Tests that there are no databases on an instance that are in a state of AutoClose, Offline, ReadOnly, Restoring, Recovery, Recovery Pending, EmergencyMode, Suspect or StandBy. Databases that are in ReadOnly,Offline and Restoring mode can be specified (default none)
Uses an assertion file and has unit tests for the assertion function
> Database status - Closes #229

- checks/Instance.Tests.ps1
This feature was introduced in SQL 2008, so anything under that will be a false flag as we can't enable the feature for those. Use the same version check as `Default Backup Compression` does.
> Skipping Ad Hoc Workload check for SQL < 2008

- checks/Database.Tests.ps1
- Adds the contents of the ExcludeDatabase parameter to the ExcludedDatabases variable that is used thoughout the checks.
> ExcludedDatabases didn't include dbs passed in on -ExcludeDatabase param

- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- Working on code for the `-Database` parameter to work for database level checks.  
This is still a bit rough, but looking for feedback.
Running this will check ValidDatabaseOwner for just the db1 database and ignore any other databases on the server. If Database is set it takes priority, so if db1 is passed in as Database but also is listed in the exclusions it will still be tested.
`Invoke-DbcCheck -Check ValidDatabaseOwner -SqlInstance server -Database db1`
I tried to handle each check in the easiest way, some that were dbatools functions had -Database params available so I used those, otherwise I used an if statement so if $Database is set match that, otherwise exclude any exclusions.
I've tested all except these two, I'll work on testing them …
> Database param - start of response to issue #509

- functions/Invoke-DbcCheck.ps1
Fixed Error:
- If PSDefaultParameterValues has already been initialized with *Dba*:Credential or *:SqlCredential, overwriting it with -Credential or -SqlCredential will fail. This happens if you set the default value 'app.sqlcredential' in your config for example and call Invoke-DbcCheck with -SqlCredential.
Fixed wrong location:
- If you use more than one dbachecks repo, as we do you need to call Pop-Location as many times as Push-Location or you will end up in one of your checks directory after Invoke-DbcCheck has finished. This can be very annoying when testing manually.
> Fixed Error when using -Credential, -SqlCredential, Fixed wrong location

- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- internal/configurations/configuration.ps1
- changed so you can pass multiple databases in on the -Database param
- removed some duplicate logic for working out the excluded databases
- fixed output for OrphanedUserTest
- fixed output for DatabaseStatusTest
old:
new:
> Databaseexists

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- Added New Check for `Two Digit Year Cutoff` configuration
- Added `policy.twodigityearcutoff` with default 2049 (SQL Server default value)
Based on my blog post [Don’t cutoff yourself with dates in T-SQL – Did you know…](https://claudioessilva.eu/2018/09/04/dont-cutoff-yourself-when-dealing-with-dates-in-t-sql-did-you-know/) and also because @shaneis (thanks man :+ ) remembered me that this was not part of dbachecks 😄
> New check - Two Digit Year Cutoff

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- tests/checks/InstanceChecks.Tests.ps1
Fixing the mess that was #538 and adding the `It` blocks correctly (I hope).
> Adding it blocks to the test file for Supported Build Checks

- Test-Pester.XML
- checks/Agent.Tests.ps1
- checks/HADR.Tests.ps1
- checks/MaintenanceSolution.Tests.ps1
- docs/functions/Set-DbcConfig.md
- functions/Invoke-DbcCheck.ps1
- functions/Reset-DbcConfig.ps1
- functions/Set-DbcConfig.ps1
- internal/assertions/Server.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/ReleaseNotes.txt
- internal/functions/New-Json.ps1
- tests/checks/DatabaseChecks.Tests.ps1
- tests/checks/InstanceChecks.Tests.ps1
- tests/checks/ServerChecks.Tests.ps1
- tests/functions/Get-CheckInformation.tests.ps1
- tests/functions/get-check.json
```## Load the module
Import-Module .\dbachecks.psd1
Invoke-Pester .\tests -ExcludeTag Integration
...
Tests Passed: 1588, Failed: 0, Skipped: 1, Pending: 0, Inconclusive: 0
```
* Spell checked all files and corrected some typos
> Corrected multiple typos

- checks/Instance.Tests.ps1
Fix dbatools command name from `Get-DbaErrorLogin` to `Get-DbaLogin`
- Fix #572 
- "SA Renamed" was calling an unexisting dbatools command. `Get-DbaErrorLogin` instead of `Get-DbaLogin`
> "SA Rename" check using wrong dbatools command name.

- internal/functions/Get-CheckInformation.ps1
Please add below the changes that this PR covers. It doesn't need an essay just the bullet points :-)
Adding this change due to best practice requiring $null on the left side of the comparison
[Best Practice](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/PossibleIncorrectComparisonWithNull.md)
> Put $null on left side

- RELEASE.md
- dbachecks.psd1
- functions/Invoke-DbcCheck.ps1
Now Import-DbcConfig does not have to run separately
> add support for inline config file, fixes #501

- checks/HADR.Tests.ps1
There are 0 failing Pester tests
A minor change to a conditional filter on the pipeline. 
Current test pulls back IP resources for the OwnerGroup 'Cluster Group' and fails because IP resource can and might be offline.
```
Name                    State   OwnerGroup       ResourceType
----                    -----   ----------       ------------
IP Address 10.253.51.51 Online  Cluster Group    IP Address
IP Address 10.253.52.51 Offline Cluster Group    IP Address
```
I believe this is original intention and all IP address resources should be ignored.
> Stop HADR checks pulling through IP resource

- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
Technically all I did was add tags.
Tags for existing CIS Audit tests.
> Issue 116 - Labeled exisiting test that are related to CIS audits

- checks/Agent.Tests.ps1
- internal/assertions/Agent.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/Unit.Tests.ps1
- tests/checks/AgentChecks.Tests.ps1
Adding 2 new checks to check for long running agent jobs
1 for current running jobs and one for last execution
both check against the average run time of the jobs
each have a skip configuration and percentage configuration
closes #239
> Long running jobs

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/checks/InstanceChecks.Tests.ps1
A CIS related check for seeing if Scan for Startup Procs is disabled.
> Issue 651 - Scan for Startup Procs 

- checks/Instance.Tests.ps1
- internal/configurations/DbcCheckDescriptions.json
Addresses #330
No failing tests.
Added a basic check, are the default file paths set as the C:\ drive? Because... they should not be.
> #330 default path checks

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/checks/InstanceChecks.Tests.ps1
Test for OLE Automation Procedures disabled.
> Issue 649 - Check for OLE Automation Proecedues to be disabled - CIS

- RELEASE.md
- dbachecks.psd1
- functions/Get-DbcCheck.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/functions/Get-CheckInformation.ps1
- tests/checks/InstanceChecks.Tests.ps1
- tests/functions/Get-CheckInformation.tests.ps1
Annoyingly adding functionality breaks things :-)
So #715 is because of the way that Get-CheckInformation parses the params to gather the tags which Get-AllInstanceINfo uses to go gather info
fixing that made the mocks for the tests fail to work as expected so I added a a group param to Get-DbcCheck
Remote Access was using the wrong propertyname
> Fixmultitags

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- CIS test for local Windows Group to not have SQL Logins
> CIS test for local Windows Group to not have SQL Logins

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
- tests/checks/InstanceChecks.Tests.ps1
- workspace.code-workspace
- CIS Check Ensure 'CHECK_POLICY' Option is set to 'ON' for All SQL Authenticated Logins
- CIS CHeck Ensure 'CHECK_EXPIRATION' Option is set to 'ON' for All SQL Authenticated Logins Within the Sysadmin Role
- CIS Check Ensure 'MUST_CHANGE' Option is set to 'ON' for All SQL Authenticated Logins for new logins
- Cleaned up two tests two user @().count instead of if for $nulls, much cleaner, BuiltIn Admin and SAExist 
Please add below the …
> CIS Login tests

- RELEASE.md
- internal/assertions/Instance.Assertions.ps1
I noticed a few things failing after updating the module on my admin workstation a while ago, but I didn't have time to debug this until today.
This is a simple case of using the wrong variable ($server) and not the variable that is used in all the other calls to dbatools cmdlets ($Instance). Another tell is that variable $server is not …
> Wrong variable used in -SqlInstance

- RELEASE.md
- checks/Agent.Tests.ps1
- checks/Instance.Tests.ps1
- dbachecks.psd1
There was some brace oddness that caused Pester to barf when it found an "else" out of place. 
I fixed the brace problem and made *slight* changes in indenting, just on the affected lines. I don't want to start up any whitespace problems which, if I look at some of the file histories, seems to be a recurring problem.
Here is what the error message looked like;
Context Testing SQL Browser Service on MARS
[-] Error occurred in Describe …
> Fix errant {braces} that broke some Browser Service checks

- RELEASE.md
- internal/assertions/Server.Assertions.ps1
Found two issues with Ping Computer. 
First, "Ping" needed a little syntax so it actually found the Count of responses. This caused the test to think that there were zero responses when in fact there were more than zero.
Second, "Average" was using a Property of "ResponseTime", which is not an attribute returned by Test-Connection. This caused a hard failure because that property does not exist.The correct attribute seems to be Latency. …
> Fix ping computer syntax issues

- dbachecks.psd1
Specify the maximum version of Pester to prevent breaking the module when Pester5 is released.
> Pin Pester version

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
- adds a config option called `skip.backup.secondaries` defaults to false
- when config is set to true the three LastBackup checks will skip any databases that are in an AG and on a secondary replica
Set up test AG with localhost, 15592 as the primary... backups are all checked on that node, but databases in the AG are skipped on the secondary node.
```
Set-DbcConfig -Name skip.backup.secondaries -Value $true
Invoke-DbcCheck -SqlInstance $sql1, $sql2 -Check LastBackup
```
> Skip option for LastBackup on AG Secondaries 

- checks/Instance.Tests.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
```
Tests completed in 37.36s
Tests Passed: 1575, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
```
- Adds a check that closes #764 
Created two config values, one to enable the check to be skipped, another for the % threshold, set at 90% for now, limit is 1000 rows.
Tested by inserting 901 rows into mssql1 suspect pages table
> New Check - suspect_pages row limit nearing

- checks/Agent.Tests.ps1
- Fix calculation for duration on job run time.
> Do math on run_duration to get actual duration

- checks/Database.Tests.ps1
$null check for anything running SQL2008R2 or below as containment doesnt exist in those versions.
CIS doc says AutoClose to be off for contained DB's so set flag to check for False and update the descriptions
> ContainedDBAutoClose

- checks/Agent.Tests.ps1
- checks/Instance.Tests.ps1
Seems IsClustered was looking at the wrong params, changed to the $InstanceSMO and now drops into the right pieces for a FCI
> Fix for IsClustered checks for service startup types

- checks/Database.Tests.ps1
CertCheck would still check the databases in the exclusion list, then filter them out at the end, this was very time consuming on a heavy used SSISDB, used the -ExcludeDatabase param on the Get-DbaDbEncryption to not even try and check certificates where the database is in the config for exclusion, so its quicker and left the original filter in as a safety net
Please add below the changes that this PR covers. It doesnt need an essay just …
> CertCheck took ages to run, was still checking excluded DB's then filtering, change to not query the excluded DBs

- checks/Database.Tests.ps1
- checks/Instance.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/configuration.ps1
DuplicateIndex Check - Added new configuration option to allow people to filter out databases, as SSRS DB's have duplicate indexes and names are configuration in older versions, defaults to ReportServer & ReportServerTempDB
GuestUserConnect - Changes method to Get-Database instead of InstanceSMO so its easier to filter out none accessable databases as the check would report false positives for offline or restoring databases
NotExpectedTraceFlag - added a filter to filter out any trace flags which WHERE expected to prevent false positive alerts
Before we accept the PR - please confirm that you have run the tests locally to avoid our automated build and release process failing. You can see how to …
> More Tweaks to Checks

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
Recent implementation of Azure Information Protection scanning resulted in a new database being created which Microsoft need to have trustworthy set to on, this chucked out the error, so to not exclude the DB from all checks, added new policy to exclude it from this one check instead
> Add policy to exclude databases on the trustworthy check

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- internal/configurations/configuration.ps1
Added a date filter for memory dumps, some of the server I check had dumps going back years, don't want to see that far back.
New policy.instance.memorydumpsdaystocheck configuration option for people to set to enable this.
Also fixed the version check as -lt resulted in 2008 servers being passed in and not gracefully failing the test, checked the version the same as Find-DbaDump does, 2008 now skip correctly
Please add below the changes …
> Date filter for memory dumps & Fix for anything 2008

- checks/Agent.Tests.ps1
- internal/configurations/DbcCheckDescriptions.json
- tests/Unit.Tests.ps1
Checks where checking that Mail XPs and a Mail Profile existed but not the the SQL Agent had been configured to use said mail profile.
Use Get-DbaAgentServer to pull out the configured DatabaseMailProfile and check it against the required database mail profile.
Systems not enabled will output empty so will fail against $null or a configured value.
This check is needed as without it you cant send alerts from the agent so the checks for email enabled alerts on Sev16-25 etc need this to be on. …
> New Check - Agent Mail Profile

- checks/Instance.Tests.ps1
- internal/assertions/Instance.Assertions.ps1
- tests/checks/InstanceChecks.Tests.ps1
The configuration option wasn't being used for ScanForStartupProcsDisabled, things like Transactional Replication need scan for startup enabling, even though config was set check would still fail
> Scan for startup procs, use config option to override the value in use

- checks/Database.Tests.ps1
Excluded databases used the wrong variable
Makes the config policy.database.filegrowthexcludedb work.
> Fixed datafile auto growth

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
- model database can't have Query store enabled but msdb can so switch that out
- test for if version is -lt 2016 rather than -ge version 13 to know if to skip
- since we have two test one for disabled and one for enabled, added skip options for both default enabled to not be skipped
> Query Store enabled and disabled test

- checks/Instance.Tests.ps1
Fix issue #782 
Using Config value "policy.errorlog.warningwindow" in the "Error Log Entries" Test makes it appear in the Get-DbcCheck output.
> Fix issue #782

- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
Two typos found on my modified 2.0.7 and vanilla 2.0.8
Database.Tests.ps1 - param is $exclude not $excluded
Database.Assertions.ps1 - CLR not CLE assemblies
> Two typos found

- checks/Agent.Tests.ps1
Some run_durations where being reported as negative numbers causing the checks to fail with conversion issues, added check for >= 0
Seemed to be some strange edge case on a couple of the servers for this issue.
> Add additional filter to filter out negative run_durations

- checks/Database.Tests.ps1
- internal/configurations/configuration.ps1
As an example, Microsoft System Centre Configuration Manager has a number of assemblies which are unrestricted as such this makes the check fail.
Added policy.database.clrassembliessafeexcludedb so that these can be excluded from the one check instead of excluded from all checks
> Add policy for additional excluded dbs from the SAFE CLR check

- checks/HADR.Tests.ps1
All Tests ran successfully on my local machine
Fix previous PR issue - HADR Tests - Adding checks
Test NetBios Over TCP/IP should be disabled for cluster network interface
> HADR - Fix NetBios Over TCP/IP check variable typo

- checks/HADR.Tests.ps1
- dbachecks.psm1
All tests ran successfully on my local machine
Fix issue #826
> Fix VERBOSE by default when importing module dbachecks

- checks/Database.Tests.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
Add LogfilePercentUsed check. Log might fill even if simple recovery model or full recovery model + Tlog backup in case of replication, CDC, HADR issues.
> Percent log used check

- checks/Database.Tests.ps1
Getting SQL Server instance DateTime prevent Log Backup checks to fail if the instance is not in the same timezone than the computer running dbaChecks scripts.
> Gettime SQL instance Date Time to avoid TZ issues

- tests/checks/DatabaseChecks.Tests.ps1
It's related to this commit:
https://github.com/sqlcollaborative/dbachecks/commit/38e3d774409c3d64fb5b3c1e604ed1c05f06ddd3#diff-fc48f8054390ae4e86ca460b687ae4c864b55f1a7f03d984a1c21f076e4d53ef
One of the [builds](https://github.com/sqlcollaborative/dbachecks/pull/838/checks?check_run_id=2291673808) failed with the errors as there was a …
> the tests to reflect changes in db assertions

- internal/functions/Get-CheckInformation.ps1
Tests Passed: 2133, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
There is existing code that evaluates what tags should be operated on during Invoke-DbaChecks. The list of tags to operate on is returned as an array. Since there are "groups" of tags and "uniquetags" and there is some logical about what can be added as part of a group, it can be that some tags are added more than once. In some cases, tags can be added multiple times. Later, tests are run based on the list of tags. If a tag is in the list twice, the corresponding test is run twice. (If a tag is in the list 42 times, it would be run 42 times and so forth.) This leads to longer execution durations, with no benefit.
This change checks to see if a tag is already in the list before …
> Check for existence in the Tag list before adding a Tag to the Tag list

- internal/assertions/Server.Assertions.ps1
- tests/checks/ServerChecks.Tests.ps1
Invoke-Pester -show Failed,Describe,Summary .\tests\Unit.Tests.ps1 is clean:
Tests Passed: 2133, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
Tiny, one-line bug fix. The original line compares $allServerInfo.PowerPlan to a string 'true', but $allServerInfo.PowerPlan needs to be compared to a boolean true. If you dig deeper, you will see that this gets set in Sever.Assertions.ps1, line 66:
$PowerPlan = (Test-DbaPowerPlan -ComputerName $ComputerName blahblahblah).IsBestPractice
It's a little weird that the 'PowerPlan' in the Server.Assertions.ps1 sets $PowerPlan to a string in the catch{} blocks when …
> The expected value is a boolean, not a string.

- functions/Invoke-DbcCheck.ps1
[x] There may or may  not be 0 failing Pester tests
Older versions of Pester such as `3.4.0` do not support the type `[Pester.OutputTypes]`. This changes that to string, and now `Invoke-DbcCheck` runs out the box on machines without newer versions of Pester.
There are no other instances of [Pester] types. Fixes #798
> Remove unsupported Pester Type - fixes #798

- internal/assertions/Instance.Assertions.ps1
* Exclude startup stored procedure for replication for test so it can past test for CIS compliance, as there is no choice but to have this as a startup procedure when you have replication.
> Remove Replication Startup procedure for test

- checks/Database.Tests.ps1
- internal/assertions/Database.Assertions.ps1
- internal/configurations/DbcCheckDescriptions.json
- internal/configurations/configuration.ps1
```
Tests completed in 18.17s
Tests Passed: 2187, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```
- New check for database snapshots older than retention period
- config property to control the retention period - default is 0 days
- config property to skip the test (not 100% sure if it needed this)
> New Check - Database snapshots older than retention period

- source/checks/Instancev5.Tests.ps1
- source/internal/functions/NewGet-AllInstanceInfo.ps1
[😄 ] There are 0 failing Pester tests
```
Running with
latestbuild
Checks against 3 SQL Containers
With original Code it takes 4.09 Seconds
With New Code it takes 4.42 Seconds
New Code for these 1 checks
is saving -0.34 seconds
from a run of 4.09 seconds
New Code runs in 108.23 % of the time
[20:05:03][Invoke-PerfAndValidateCheck]
The Tags are the same
[20:05:03][Invoke-PerfAndValidateCheck]
The Total Tests Run are the same 3 3
[20:05:03][Invoke-PerfAndValidateCheck]
The …
```
> Add latestbuild check

- readme.md
> we paused v2

- containers/JessAndBeard.psm1
- developing/Robs-Instance.ps1
- readme.md
- source/checks/Instancev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/NewGet-AllInstanceInfo.ps1
Added 3 more checks to the #882 Instance level checks
> Moreinstancechecks

- source/checks/Databasev5.Tests.ps1
- source/internal/configurations/configuration.ps1
- source/internal/functions/Get-AllDatabaseInfo.ps1
Adding a new check for `GuestUserConnect` - but I think there is an issue with the original check so my results aren't matching.
I have run the following against `localhost,7401` and the old test is saying we're good - but the new test correctly identifies the issue.
Wouldn't if someone could confirm my suspicions before we merge it in - cc @SQLDBAWithABeard, @ClaudioESSilva 
```sql
USE pubs
GO
GRANT CONNECT TO guest
```
Running `Invoke-PerfAndValidateCheck` says we have issues...
``` PowerShell
╰─ﬀ Invoke-PerfAndValidateCheck -SQLInstances $sqlinstances -Checks $Checks -showTestResults
Running in PowerShell 7.3.4 64-bit.
Starting trace.
Stopwatch is high resolution, max resolution of timestamps is 100ns.
[16:12:48][Invoke-DbcCheckv4]
Key        Value
---        -----
Script …
```
> New check - GuestUserConnect

- source/checks/Instancev5.Tests.ps1
- source/functions/Invoke-DbcCheck.ps1
- source/internal/functions/Invoke-DbcCheckv5.ps1
- source/internal/functions/NewGet-AllInstanceInfo.ps1
> so that we can see failed connections and they are in the results #882

- containers/JessAndBeard.psm1
- source/checks/Instancev5.Tests.ps1
- source/functions/Invoke-DbcCheck.ps1
- source/internal/configurations/configuration.ps1
> So we can ignore existing checks and dont have output

- azure-pipelines.yml
- codecov.yml
- docs/index.md
- header-mkdocs.yml
- mkdocs.yml
- readme.md
Fixed branch rename left over docs and links to edit
[?] There are 0 failing Pester tests
I updated the docs, so no clue
* Corrected the outdated "Master Branch" terminology to "Main Branch" in the documentation links.
* Corrected it in the readthedocs config so the `edit` buttons there point to the correct branch
Wasn't sure if this would break anything in the build projects
* GitVersion.yml refers to master
* tests/Project.Tests.ps1
> Fixed branch rename in documentation links

- CHANGELOG.md
- containers/JessAndBeard.psm1
> Fix typo so we know which is v5
